# Generated by Django 4.2 on 2023-05-20 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactions',
            options={'verbose_name_plural': 'transactions'},
        ),
    ]
